steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
    - 'build'
    - '--tag=$_DOCKER_REGISTRY/$_APP_NAME:$_VERSION'
    - '--file=$_DOCKER_FILE_PATH'
    - '.'


  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_DOCKER_REGISTRY/$_APP_NAME:$_VERSION']

substitutions:
  _DOCKER_REGISTRY: khhini
  _APP_NAME: todo-app-api
  _VERSION: rust-${SHORT_SHA}
  _DOCKER_FILE_PATH: deployments/docker/Dockerfile

options:
  dynamicSubstitutions: true
  logging: CLOUD_LOGGING_ONLY